name: unbounded
description: A simple snake game... maybe?
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hive: ^2.0.4
  cupertino_icons: ^1.0.2
  equatable: ^2.0.2
  sensors_plus: ^1.0.1
  google_fonts: ^2.1.0
  redux: ^5.0.0
  vector_math: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.16.8
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
