name: unbounded
description: A new Flutter project.
publish_to: none

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dotted_border: ^2.0.0+1
  flame: ^1.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.5.3

flutter:
  uses-material-design: true
